### ISSUE TITLE
Might not need to pass Authentication Result to API invocation flow

### ISSUE THREAD

**Issue by imesh** [wso2-incubator/azure-artifacts#7]
Currently, it seems like API invocation flow has used Authentication Result object instead of the access token for making the API calls:

``` java
protected List<String> findVMIPaddresses(AuthenticationResult result, String subscriptionID, String resourceGroup,
            String networkSecurityGroup, String networkInterfaceTag) throws AzureMembershipSchemeException {
...
}
```

https://github.com/wso2-incubator/azure-artifacts/blob/master/src/main/java/org/wso2/carbon/clustering/azure/AzureMembershipScheme.java#L137

**Comment by Thanu** [comment]
This is fixed in commit[[1](https://github.com/wso2-incubator/azure-common/commit/5c50ad5491fc57c1faaf49c33152ec943ec3d7f5)] by imesh.
